version: '2.1'

services:
  app:
    build: .
    environment:
      - MODE=dev
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - GRAYLOG_HOST=graylog
      - GRAYLOG_PORT=12201
    volumes:
      - .:/code
    depends_on:
      - elasticsearch
      - rabbitmq
      - graylog
    ports:
      - "9091:9090"
      
  rabbitmq:
    image: rabbitmq:3.6.1-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "8023:15672"
      - "8024:5672"
#    healthcheck:
#        test: ["CMD", "curl", "-f", "http://localhost:15672"]
#        interval: 30s
#        timeout: 10s
#        retries: 5

  elasticsearch:
    image: elasticsearch:5-alpine
    restart: unless-stopped
    command: elasticsearch -Etransport.host=127.0.0.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9200"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
    volumes:
      - ../data:/usr/share/elasticsearch/data

  some-mongo:
    image: "mongo:3"

  some-elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"

  graylog:
    image: graylog2/server:2.1.1-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - some-mongo:mongo
      - some-elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"